/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('bookings').del()
  await knex('bookings').insert([//google-oauth2|115329107932736690149 // zac
    {
      id: 1,
      court_id: 1,
      user_id: 'google-oauth2|115733908984871137690',
      date: new Date(2024, 6, 12),
      start_time: 900,
      end_time: 1030,
      gear_rental: false,
      price: 18,
      paid: true,
    },
    {
      id: 2,
      court_id: 2,
      user_id: 'google-oauth2|115733908984871137690',
      date: new Date(2024, 6, 13),
      start_time: 1000,
      end_time: 1130,
      gear_rental: true,
      price: 25,
      paid: true,
    },
    {
      id: 3,
      court_id: 3,
      user_id: 3,
      date: new Date(2024, 6, 14),
      start_time: 1100,
      end_time: 1230,
      gear_rental: false,
      price: 20,
      paid: false,
    },
    {
      id: 4,
      court_id: 4,
      user_id: 4,
      date: new Date(2024, 6, 15),
      start_time: 1200,
      end_time: 1330,
      gear_rental: true,
      price: 30,
      paid: true,
    },
    {
      id: 5,
      court_id: 1,
      user_id: 5,
      date: new Date(2024, 6, 16),
      start_time: 1300,
      end_time: 1430,
      gear_rental: false,
      price: 15,
      paid: true,
    },
    {
      id: 6,
      court_id: 2,
      user_id: 6,
      date: new Date(2024, 6, 17),
      start_time: 1400,
      end_time: 1530,
      gear_rental: true,
      price: 20,
      paid: false,
    },
    {
      id: 7,
      court_id: 3,
      user_id: 1,
      date: new Date(2024, 6, 18),
      start_time: 1500,
      end_time: 1630,
      gear_rental: false,
      price: 18,
      paid: true,
    },
    {
      id: 8,
      court_id: 4,
      user_id: 2,
      date: new Date(2024, 6, 12),
      start_time: 1600,
      end_time: 1730,
      gear_rental: true,
      price: 25,
      paid: true,
    },
    {
      id: 9,
      court_id: 1,
      user_id: 3,
      date: new Date(2024, 6, 13),
      start_time: 1700,
      end_time: 1830,
      gear_rental: false,
      price: 20,
      paid: false,
    },
    {
      id: 10,
      court_id: 2,
      user_id: 4,
      date: new Date(2024, 6, 14),
      start_time: 1800,
      end_time: 1930,
      gear_rental: true,
      price: 30,
      paid: true,
    },
    {
      id: 11,
      court_id: 3,
      user_id: 5,
      date: new Date(2024, 6, 15),
      start_time: 1900,
      end_time: 2030,
      gear_rental: false,
      price: 15,
      paid: true,
    },
    {
      id: 12,
      court_id: 4,
      user_id: 6,
      date: new Date(2024, 6, 16),
      start_time: 2000,
      end_time: 2130,
      gear_rental: true,
      price: 20,
      paid: false,
    },
    {
      id: 13,
      court_id: 1,
      user_id: 1,
      date: new Date(2024, 6, 17),
      start_time: 2100,
      end_time: 2230,
      gear_rental: false,
      price: 18,
      paid: true,
    },
    {
      id: 14,
      court_id: 2,
      user_id: 2,
      date: new Date(2024, 6, 18),
      start_time: 2200,
      end_time: 2330,
      gear_rental: true,
      price: 25,
      paid: true,
    },
    {
      id: 15,
      court_id: 3,
      user_id: 3,
      date: new Date(2024, 6, 12),
      start_time: 800,
      end_time: 930,
      gear_rental: false,
      price: 20,
      paid: false,
    },
    {
      id: 16,
      court_id: 4,
      user_id: 4,
      date: new Date(2024, 6, 13),
      start_time: 700,
      end_time: 830,
      gear_rental: true,
      price: 30,
      paid: true,
    },
    {
      id: 17,
      court_id: 1,
      user_id: 5,
      date: new Date(2024, 6, 14),
      start_time: 600,
      end_time: 730,
      gear_rental: false,
      price: 15,
      paid: true,
    },
    {
      id: 18,
      court_id: 2,
      user_id: 6,
      date: new Date(2024, 6, 15),
      start_time: 500,
      end_time: 630,
      gear_rental: true,
      price: 20,
      paid: false,
    },
    {
      id: 19,
      court_id: 3,
      user_id: 1,
      date: new Date(2024, 6, 16),
      start_time: 400,
      end_time: 530,
      gear_rental: false,
      price: 18,
      paid: true,
    },
    {
      id: 20,
      court_id: 4,
      user_id: 2,
      date: new Date(2024, 6, 17),
      start_time: 300,
      end_time: 430,
      gear_rental: true,
      price: 25,
      paid: true,
    },
  ])
}

// let date: Date = new Date("2019-01-16")
// console.log(date)

// export const up = function (knex) {
//   return knex.schema.createTable('bookings', (table) => {
//     table.integer('id').primary()
//     table.foreign('court_id').references('id').inTable('courts')
//     table.foreign('user_id').references('id').inTable('users')
//     table.date('date')
//     table.time('start_time')
//     table.time('end_time')
//     table.boolean('gear_rental')
//     table.decimal('price', 5, 2)
//     table.boolean('paid')
//   })
// }
